name: Landing CI

on:
  push:
    branches:
      - main

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verificar index.html
        run: test -f index.html

      - name: Verificar css/style.css
        run: test -f css/style.css

      - name: Verificar js/script.js
        run: test -f js/script.js

      - name: Validación completada
        run: echo "Proyecto validado correctamente"
